KOSTAL_MODBUS_REGISTERS = {
    # 3.1: TCP-Port / Unit-ID (nur Info)
    # TCP-Port: 1502, Unit-ID default: 71

    # 3.2 Query the operating data
    2:   {"addr_hex": "0x02", "description": "MODBUS Enable",
          "unit": None, "datatype": "Bool", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    4:   {"addr_hex": "0x04", "description": "MODBUS Unit-ID",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    5:   {"addr_hex": "0x05", "description": "MODBUS Byte Order (Note7)",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    6:   {"addr_hex": "0x06", "description": "Inverter article number",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    14:  {"addr_hex": "0x0E", "description": "Inverter serial number",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    30:  {"addr_hex": "0x1E", "description": "Number of bidirectional converter",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    32:  {"addr_hex": "0x20", "description": "Number of AC phases",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    34:  {"addr_hex": "0x22", "description": "Number of PV strings",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    36:  {"addr_hex": "0x24", "description": "Hardware-Version",
          "unit": None, "datatype": "U16", "registers": 2,
          "access": "RO", "function": "0x03"},
    38:  {"addr_hex": "0x26", "description": "Software-Version Maincontroller (MC)",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    46:  {"addr_hex": "0x2E", "description": "Software-Version IO-Controller (IOC)",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    54:  {"addr_hex": "0x36", "description": "Power-ID",
          "unit": None, "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    56:  {"addr_hex": "0x38", "description": "Inverter state",
          "unit": None, "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    58:  {"addr_hex": "0x3A", "description": "Overall software version (UI / SW)",
          "unit": None, "datatype": "String", "registers": 13,
          "access": "RO", "function": "0x03"},

    98:  {"addr_hex": "0x62", "description": "Temperature of controller PCB",
          "unit": "°C", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    100: {"addr_hex": "0x64", "description": "Total DC power",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    104: {"addr_hex": "0x68", "description": "State of energy manager",
          "unit": None, "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    106: {"addr_hex": "0x6A", "description": "Home own consumption from battery",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    108: {"addr_hex": "0x6C", "description": "Home own consumption from grid",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    110: {"addr_hex": "0x6E", "description": "Total home consumption Battery",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    112: {"addr_hex": "0x70", "description": "Total home consumption Grid",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    114: {"addr_hex": "0x72", "description": "Total home consumption PV",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    116: {"addr_hex": "0x74", "description": "Home own consumption from PV",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    118: {"addr_hex": "0x76", "description": "Total home consumption",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    120: {"addr_hex": "0x78", "description": "Isolation resistance",
          "unit": "Ohm", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    122: {"addr_hex": "0x7A", "description": "Power limit from EVU",
          "unit": "%", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    124: {"addr_hex": "0x7C", "description": "Total home consumption rate",
          "unit": "%", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},

    144: {"addr_hex": "0x90", "description": "Worktime",
          "unit": "s", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    150: {"addr_hex": "0x96", "description": "Actual cos φ",
          "unit": None, "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    152: {"addr_hex": "0x98", "description": "Grid frequency",
          "unit": "Hz", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    154: {"addr_hex": "0x9A", "description": "Current Phase 1",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    156: {"addr_hex": "0x9C", "description": "Active power Phase 1",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    158: {"addr_hex": "0x9E", "description": "Voltage Phase 1",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    160: {"addr_hex": "0xA0", "description": "Current Phase 2",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    162: {"addr_hex": "0xA2", "description": "Active power Phase 2",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    164: {"addr_hex": "0xA4", "description": "Voltage Phase 2",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    166: {"addr_hex": "0xA6", "description": "Current Phase 3",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    168: {"addr_hex": "0xA8", "description": "Active power Phase 3",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    170: {"addr_hex": "0xAA", "description": "Voltage Phase 3",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    172: {"addr_hex": "0xAC", "description": "Total AC active power",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    174: {"addr_hex": "0xAE", "description": "Total AC reactive power",
          "unit": "Var", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    178: {"addr_hex": "0xB2", "description": "Total AC apparent power",
          "unit": "VA", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},

    190: {"addr_hex": "0xBE", "description": "Battery charge current",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    194: {"addr_hex": "0xC2", "description": "Number of battery cycles",
          "unit": None, "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    200: {"addr_hex": "0xC8", "description": "Actual battery charge (-) / discharge (+) current",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    202: {"addr_hex": "0xCA", "description": "PSSB fuse state",
          "unit": None, "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    208: {"addr_hex": "0xD0", "description": "Battery ready flag",
          "unit": None, "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    210: {"addr_hex": "0xD2", "description": "Act. state of charge",
          "unit": "%", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    214: {"addr_hex": "0xD6", "description": "Battery temperature",
          "unit": "°C", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    216: {"addr_hex": "0xD8", "description": "Battery voltage",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},

    218: {"addr_hex": "0xDA", "description": "Cos φ (powermeter)",
          "unit": None, "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    220: {"addr_hex": "0xDC", "description": "Frequency (powermeter)",
          "unit": "Hz", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    222: {"addr_hex": "0xDE", "description": "Current phase 1 (powermeter)",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    224: {"addr_hex": "0xE0", "description": "Active power phase 1 (powermeter)",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    226: {"addr_hex": "0xE2", "description": "Reactive power phase 1 (powermeter)",
          "unit": "Var", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    228: {"addr_hex": "0xE4", "description": "Apparent power phase 1 (powermeter)",
          "unit": "VA", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    230: {"addr_hex": "0xE6", "description": "Voltage phase 1 (powermeter)",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    232: {"addr_hex": "0xE8", "description": "Current phase 2 (powermeter)",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    234: {"addr_hex": "0xEA", "description": "Active power phase 2 (powermeter)",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    236: {"addr_hex": "0xEC", "description": "Reactive power phase 2 (powermeter)",
          "unit": "Var", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    238: {"addr_hex": "0xEE", "description": "Apparent power phase 2 (powermeter)",
          "unit": "VA", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    240: {"addr_hex": "0xF0", "description": "Voltage phase 2 (powermeter)",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    242: {"addr_hex": "0xF2", "description": "Current phase 3 (powermeter)",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    244: {"addr_hex": "0xF4", "description": "Active power phase 3 (powermeter)",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    246: {"addr_hex": "0xF6", "description": "Reactive power phase 3 (powermeter)",
          "unit": "Var", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    248: {"addr_hex": "0xF8", "description": "Apparent power phase 3 (powermeter)",
          "unit": "VA", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    250: {"addr_hex": "0xFA", "description": "Voltage phase 3 (powermeter)",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},

    252: {"addr_hex": "0xFC", "description": "Total active power (powermeter)",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    254: {"addr_hex": "0xFE", "description": "Total reactive power (powermeter)",
          "unit": "Var", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    256: {"addr_hex": "0x100", "description": "Total apparent power (powermeter)",
          "unit": "VA", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},

    258: {"addr_hex": "0x102", "description": "Current DC1",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    260: {"addr_hex": "0x104", "description": "Power DC1",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    266: {"addr_hex": "0x10A", "description": "Voltage DC1",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    268: {"addr_hex": "0x10C", "description": "Current DC2",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    270: {"addr_hex": "0x10E", "description": "Power DC2",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    276: {"addr_hex": "0x114", "description": "Voltage DC2",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    278: {"addr_hex": "0x116", "description": "Current DC3",
          "unit": "A", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    280: {"addr_hex": "0x118", "description": "Power DC3",
          "unit": "W", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    286: {"addr_hex": "0x11E", "description": "Voltage DC3",
          "unit": "V", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},

    320: {"addr_hex": "0x140", "description": "Total yield",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    322: {"addr_hex": "0x142", "description": "Daily yield",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    324: {"addr_hex": "0x144", "description": "Yearly yield",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},
    326: {"addr_hex": "0x146", "description": "Monthly yield",
          "unit": "Wh", "datatype": "Float", "registers": 2,
          "access": "RO", "function": "0x03"},

    384: {"addr_hex": "0x180", "description": "Inverter network name",
          "unit": None, "datatype": "String", "registers": 32,
          "access": "RO", "function": "0x03"},
    416: {"addr_hex": "0x1A0", "description": "IP enable",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    418: {"addr_hex": "0x1A2", "description": "Manual IP / Auto-IP",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    420: {"addr_hex": "0x1A4", "description": "IP-address",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    428: {"addr_hex": "0x1AC", "description": "IP-subnetmask",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    436: {"addr_hex": "0x1B4", "description": "IP-gateway",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    444: {"addr_hex": "0x1BC", "description": "IP-auto-DNS",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    446: {"addr_hex": "0x1BE", "description": "IP-DNS1",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    454: {"addr_hex": "0x1C6", "description": "IP-DNS2",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},

    512: {"addr_hex": "0x200", "description": "Battery gross capacity",
          "unit": "Ah", "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    514: {"addr_hex": "0x202", "description": "Battery actual SOC",
          "unit": "%", "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    515: {"addr_hex": "0x203", "description": "Firmware Maincontroller (MC)",
          "unit": None, "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    517: {"addr_hex": "0x205", "description": "Battery Manufacturer",
          "unit": None, "datatype": "String", "registers": 8,
          "access": "RO", "function": "0x03"},
    525: {"addr_hex": "0x20D", "description": "Battery Model ID",
          "unit": None, "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    527: {"addr_hex": "0x20F", "description": "Battery Serial Number",
          "unit": None, "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    529: {"addr_hex": "0x211", "description": "Work Capacity",
          "unit": "Wh", "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    531: {"addr_hex": "0x213", "description": "Inverter Max Power",
          "unit": "W", "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},
    532: {"addr_hex": "0x214", "description": "Inverter Max Power Scale Factor",
          "unit": None, "datatype": None, "registers": 1,
          "access": "RO", "function": "0x03"},
    533: {"addr_hex": "0x215", "description": "Active Power Setpoint",
          "unit": "%", "datatype": "U16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    535: {"addr_hex": "0x217", "description": "Inverter Manufacturer",
          "unit": None, "datatype": "String", "registers": 16,
          "access": "RO", "function": "0x03"},
    559: {"addr_hex": "0x22F", "description": "Inverter Serial Number",
          "unit": None, "datatype": "String", "registers": 16,
          "access": "RO", "function": "0x03"},
    575: {"addr_hex": "0x23F", "description": "Inverter Generation Power (actual)",
          "unit": "W", "datatype": "S16", "registers": 1,
          "access": "RO", "function": "0x03"},
    576: {"addr_hex": "0x240", "description": "Power Scale Factor",
          "unit": None, "datatype": None, "registers": 1,
          "access": "RO", "function": "0x03"},
    577: {"addr_hex": "0x241", "description": "Generation Energy",
          "unit": "Wh", "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    579: {"addr_hex": "0x243", "description": "Energy Scale Factor",
          "unit": None, "datatype": None, "registers": 1,
          "access": "RO", "function": "0x03"},
    582: {"addr_hex": "0x246", "description": "Actual battery charge/discharge power",
          "unit": "W", "datatype": "S16", "registers": 1,
          "access": "RO", "function": "0x03"},
    583: {"addr_hex": "0x247", "description": "Reactive Power Setpoint",
          "unit": "%", "datatype": "S16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    585: {"addr_hex": "0x249", "description": "Delta-cos φ Setpoint",
          "unit": None, "datatype": "S16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    586: {"addr_hex": "0x24A", "description": "Battery Firmware",
          "unit": None, "datatype": "U32", "registers": 2,
          "access": "RO", "function": "0x03"},
    588: {"addr_hex": "0x24C", "description": "Battery Type",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RO", "function": "0x03"},

    608: {"addr_hex": "0x260", "description": "I/O-Board, Switched Output 1",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    609: {"addr_hex": "0x261", "description": "I/O-Board, Switched Output 2",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    610: {"addr_hex": "0x262", "description": "I/O-Board, Switched Output 3",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},
    611: {"addr_hex": "0x263", "description": "I/O-Board, Switched Output 4",
          "unit": None, "datatype": "U16", "registers": 1,
          "access": "RW", "function": "0x03/0x06"},

    768: {"addr_hex": "0x300", "description": "Productname (e.g. PLENTICORE plus)",
          "unit": None, "datatype": "String", "registers": 32,
          "access": "RO", "function": "0x03"},
    800: {"addr_hex": "0x320", "description": "Power class (e.g. 10)",
          "unit": None, "datatype": "String", "registers": 32,
          "access": "RO", "function": "0x03"},

    1046: {"addr_hex": "0x416", "description": "Total DC charge energy (DC-side to battery)",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1048: {"addr_hex": "0x418", "description": "Total DC discharge energy (DC-side from battery)",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1050: {"addr_hex": "0x41A", "description": "Total AC charge energy (AC-side to battery)",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1052: {"addr_hex": "0x41C", "description": "Total AC discharge energy (battery to grid)",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1054: {"addr_hex": "0x41E", "description": "Total AC charge energy (grid to battery)",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1056: {"addr_hex": "0x420", "description": "Total DC PV energy (sum of all PV inputs)",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1058: {"addr_hex": "0x422", "description": "Total DC energy from PV1",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1060: {"addr_hex": "0x424", "description": "Total DC energy from PV2",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1062: {"addr_hex": "0x426", "description": "Total DC energy from PV3",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1064: {"addr_hex": "0x428", "description": "Total energy AC-side to grid",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1066: {"addr_hex": "0x42A", "description": "Total DC power (sum of all PV inputs)",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},

    # 3.4 External battery management (erster Block, 0x400ff)
    1024: {"addr_hex": "0x400", "description": "Battery charge power (AC) setpoint",
           "unit": "W", "datatype": "S16", "registers": 1,
           "access": "RO", "function": "0x06"},
    1025: {"addr_hex": "0x401", "description": "Power Scale Factor",
           "unit": None, "datatype": "S16", "registers": 1,
           "access": "RO", "function": "0x03"},
    1026: {"addr_hex": "0x402", "description": "Battery charge power (AC) setpoint, absolute",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1028: {"addr_hex": "0x404", "description": "Battery charge current (DC) setpoint, relative",
           "unit": "%", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1030: {"addr_hex": "0x406", "description": "Battery charge power (AC) setpoint, relative",
           "unit": "%", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1032: {"addr_hex": "0x408", "description": "Battery charge current (DC) setpoint, absolute",
           "unit": "A", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1034: {"addr_hex": "0x40A", "description": "Battery charge power (DC) setpoint, absolute",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1036: {"addr_hex": "0x40C", "description": "Battery charge power (DC) setpoint, relative",
           "unit": "%", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1038: {"addr_hex": "0x40E", "description": "Battery max. charge power limit, absolute",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1040: {"addr_hex": "0x410", "description": "Battery max. discharge power limit, absolute",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1042: {"addr_hex": "0x412", "description": "Minimum SOC",
           "unit": "%", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1044: {"addr_hex": "0x414", "description": "Maximum SOC",
           "unit": "%", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},

    1068: {"addr_hex": "0x42C", "description": "Battery work capacity",
           "unit": "Wh", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1070: {"addr_hex": "0x42E", "description": "Battery serial number",
           "unit": None, "datatype": "U32", "registers": 2,
           "access": "RO", "function": "0x03"},
    1072: {"addr_hex": "0x430", "description": "Reserved",
           "unit": None, "datatype": None, "registers": 2,
           "access": "RO", "function": "0x03"},
    1074: {"addr_hex": "0x432", "description": "Reserved",
           "unit": None, "datatype": None, "registers": 2,
           "access": "RO", "function": "0x03"},
    1076: {"addr_hex": "0x434", "description": "Maximum charge power limit (read-out from battery)",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1078: {"addr_hex": "0x436", "description": "Maximum discharge power limit (read-out from battery)",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RO", "function": "0x03"},
    1080: {"addr_hex": "0x438", "description": "Battery management mode",
           "unit": None, "datatype": "U8", "registers": 1,
           "access": "RO", "function": "0x03"},
    1081: {"addr_hex": "0x439", "description": "Reserved",
           "unit": None, "datatype": None, "registers": 1,
           "access": "RO", "function": "0x03"},
    1082: {"addr_hex": "0x43A", "description": "Installed sensor type",
           "unit": None, "datatype": "U8", "registers": 1,
           "access": "RO", "function": "0x03"},

    # 3.3 Active power and reactive power control – zusätzliche Register
    832: {"addr_hex": "0x340", "description": "Low-Priority Active power setpoint (W)",
          "unit": "W", "datatype": "U16", "registers": 1,
          "access": "WO", "function": "0x06"},
    833: {"addr_hex": "0x341", "description": "Low-Priority Active power setpoint scale factor",
          "unit": None, "datatype": "S8", "registers": 1,
          "access": "RO", "function": "0x03"},

    # 3.5 External battery management (Limitierung, nur G3)
    1280: {"addr_hex": "0x500", "description": "Max battery charge power",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1282: {"addr_hex": "0x502", "description": "Max battery discharge power",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1284: {"addr_hex": "0x504", "description": "Max battery charge power (fallback case)",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1286: {"addr_hex": "0x506", "description": "Max battery discharge power (fallback case)",
           "unit": "W", "datatype": "Float", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},
    1288: {"addr_hex": "0x508", "description": "Time until fallback",
           "unit": "s", "datatype": "U32", "registers": 2,
           "access": "RW", "function": "0x03/0x10"},

    # Hohe Adressen (Energie Import/Export)
    40346: {"addr_hex": "0x9D9A", "description": "Total Real Energy Exported",
            "unit": "Wh", "datatype": "U32", "registers": 2,
            "access": "RO", "function": "0x03"},
    40354: {"addr_hex": "0x9DA2", "description": "Total Real Energy Imported",
            "unit": "Wh", "datatype": "U32", "registers": 2,
            "access": "RO", "function": "0x03"},
}
